### PR TITLE
Fixing the issue

### PR DESCRIPTION
**Pull request by eliasmaia**
Hi @danthareja ,

First of all, thanks for having this idea, for putting this up. Thank you for concepting this idea for letting us participate of the contribution process here on Github. Plus, at the way you made it, we are not just adding a line with our names at a text file, but, even being a small and simple problem, we have to think about it and spend some time trying to solve it. So, thank you!

By the way, in the beginning I was very confused of what needed to be done, till I understood. Then, it got easy. Also, I think to set up all the identation and space in the code was more time consuming and hard for me than the code challenge itself (I am not saying the code challenge was easy), because it was something new to me, to solve that kinda problem. Even the error descriptions were new to me, but in the end, I made it. 

Well, thanks again @danthareja ! Keep up the good work!

By the way, I'm glad that, during the completion of this, I got to learn some things about node, about npm, about dependencies, npm install and other things. Thank you!  

- [X]  Read the contributing guidelines
- [X] Build the project locally
- [X] Go to this line and change describe.skip to describe.only
- [X] Run npm test
- [X] Notice that the tests are failing
- [X] Implement _check to make the tests pass
- [X] Change the describe.only to describe so all the tests run
- [X] Run npm test again
- [X] Make sure that all the tests are passing
- [X] Submit a pull request

### CODE REVIEW

**Comment by eliasmaia** [comment]
> 
> 
> I ran your code and everything looks great.
> 
> Thanks for your contribution @eliasmaia!
> 
> Your code style completely follows the [style guide](https://github.com/danthareja/contribute-to-open-source/blob/master/CONTRIBUTING.md#style-guide). Nice job!
> 
> All the tests are passing. Nice job!
> 
> ✅ _check should throw a TypeError if arguments are not numbers
> ✅ _check should be called once in "add"
> ✅ _check should be called once in "subtract"
> ✅ _check should be called once in "multiply"
> ✅ _check should be called once in "divide"
> ✅ add should throw a TypeError if arguments are not numbers
> ✅ add should add two positive numbers
> ✅ add should add two negative numbers
> ✅ add should add one positive number and one negative number
> ✅ subtract should throw a TypeError if arguments are not numbers
> ✅ subtract should subtract two positive numbers
> ✅ subtract should subtract two negative numbers
> ✅ subtract should subtract one positive number and one negative number
> ✅ multiply should throw a TypeError if arguments are not numbers
> ✅ multiply should multiply two positive numbers
> ✅ multiply should multiply two negative numbers
> ✅ multiply should multiply one positive number and one negative number
> ✅ divide should throw a TypeError if arguments are not numbers
> ✅ divide should divide two positive numbers
> ✅ divide should divide two negative numbers
> ✅ divide should divide one positive number and one negative number

Thank you so much, @danthareja !

**Comment by eliasmaia** [comment]
Hi there, 

Can I still talk about some doubts I have in this place?

**Comment by danthareja** [comment]
thanks for the thorough response @eliasmaia, I'm glad you persevered through the exercise and learned a thing or two.

what kind of doubts do you still have?

**Comment by eliasmaia** [comment]
You're welcome! You deserved that response! Thanks again! 

I was just wondering why the commits I made at my fork of this repo did not show up as contributions on my profile of github. 

com

As you can see, it only counts the pull requests and the creation of the repo.

I think I did 3 commits, in the fork, so, I expected to see them being counted.

Do you know what happened, and why? :D

**Comment by danthareja** [comment]
That’s a good question!

Unfortunately I don’t have an answer for you. This is GitHub-specific behavior so you might find an answer in the GitHub docs somewhere or you might be able to reach out to support.

It could be as simple as fork activity  are not accounted for.

**Comment by eliasmaia** [comment]
Or maybe that happened because I did not create a branch when answering the issue. I don't know. Well, thank you anyway!

**Comment by eliasmaia** [comment]
No worries! 
Thanks again for putting all of this together! 
Happy hacking!

**Pull request merged**
