### PR TITLE
calculator.js file updated with DRY code + functionality for add/subt…

### PR DESCRIPTION
**Pull request by wallythewebdev**
…ract/multiply/devide - passing all tests

**Delete me and write your Pull Request message here!**

### CODE REVIEW

**Comment by wallythewebdev** [comment]
Hi Dan - 

I seem to be really running into some issues when trying to make a pull request here - bit odd but figured Id ask for a bit of guidance - 

Below are the setting that are failing could you please give me some advice on how / what should be changed? 

Thanks in advance, 
Walter 

pull Request

**Comment by danthareja** [comment]
Hey, you found a bug @wallythewebdev! You're the first user who has authored commits on a different user's repo. 

Right now, the guard that closes these PRs checks whether the logged in user making the pull request (@wallythewebdev) is the same as the user in the base branch (@openSource-wallythewebdev).

Historically, this guard was put in place to prevent users making pull requests on behalf of other users.

One solution would be to open this pull request from your @openSource-wallythewebdev account, otherwise I can look into supporting multi-user PRs. What do you think?

**Comment by wallythewebdev** [comment]
HI Dan - 

That's really cool to know I was the first person doing that and thank you for your reply! I was worried that I was making some silly mistake (which might still be the case). 

I decided to section my work into different organizations on gitHub i.e 

frontend-wallythewebdev
backend-wallythewebdev & 
openSource-wallythewebdev

But it is me as the user with different organizations rather than a different account (unless git hub classes different organizations as different accounts). 

I'd be happy to try and tweek my approach by your suggestion, there might not be a need to the work put into looking into supporting multi-user PRs (as I am the only person to experience the issue).

**Comment by danthareja** [comment]
Ah, I didn't realize @openSource-wallythewebdev was an organization, I thought it was another user account you owned. You're definitely the first person to fork this repo into an organization. How interesting!

As for completing this exercise, the fastest thing would be to fork this repo into your personal account @wallythewebdev, and re-submit a PR from that repo. However, the conversion is the most important part of a PR, which you're getting experience with by having this conversation 😁

If you'd like, I can look into organization support, but I have to admit it's a rather unconventional setup for a single person to have. Can I ask why you chose to open multiple orgs for yourself?

**Comment by wallythewebdev** [comment]
Ok I can fork the project into my main account - and even more cool to note that I am the only person running it thought an organization. I chose this set up to make it a little easier for me to show case work to a potential employer, I figured that it would be a good way to organize my repos (pains of trying to land that first official developer job).

Could you expand a little on "the conversion is the most important part of a PR" I'm interested but might not have fully understood (thanks in advance) 

It seems like I've taken a different approach than the norm so maybe it would be easier for me to just change my approach rather than you cater for the (probably less than) 1%. 

Thanks again for the reply

**Comment by danthareja** [comment]
I see. I think it's still a bit unconventional, but that's great if it works for you!

All I mean is that opening a pull request is starts a conversation with the repo owner about proposing your change. In addition to the code in your proposed change, the conversation between you and the repo owner (me, in this case), is an important part of the process.

You did a great job proposing your question, providing sufficient details when asked, and asking for clarification when necessary. It's been a pleasure having a conversation with you and I wish you the very best of luck in your web dev journey.

**Comment by wallythewebdev** [comment]
HI Dan, 

Ah I see ok sorry must have misread that part about opening the convocation and yes totally agree. 

Thank you for the kind words and help on the subject, have an amazing week ahead. 

Wally

**Pull request closed without merging**
