### PR TITLE
Implement _check function

### PR DESCRIPTION
**Pull request by polinadotio**
Thanks for setting this up! I've tried 2 other repos before that let you submit hello world pull requests directly to their repo: https://github.com/jlord/git-it-electron and https://github.com/hoodiehq/camp/issues/132 in case you're interested in seeing how others are setting up their tutorials.

### CODE REVIEW

**Comment by danthareja** [comment]
Thanks for the submission, @polinadotio.

As mentioned in the [contributing guidelines](https://github.com/danthareja/contribute-to-open-source/blob/master/CONTRIBUTING.md#open-a-pull-request), I can only accept a pull request made to *your branch*. This is a restriction unique to this particular project that allows multiple people to contribute code.

Please [open another pull request](https://github.com/danthareja/contribute-to-open-source/compare/polinadotio...polinadotio:master) with the following values:

* **base fork:** `danthareja/contribute-to-open-source`
* **base:** `polinadotio`
* **head fork:** `polinadotio/contribute-to-open-source`
* **compare:** `master`

I'll happily review that one :smile_cat:

**Comment by polinadotio** [comment]
@danthareja oh interesting. I'll pass for now : ) That's a little strange because it doesn't reflect what you would do in a real project, but I get what you're trying to get across.

**Comment by danthareja** [comment]
Thanks for the project links @polinadotio, I'm definitely going to look into them.

I know the fake branch solution isn't ideal, but it's the only think I could think of to allow multiple users to do the same challenge. Do you have any other ideas?

**Comment by danthareja** [comment]
Thanks for the project links @polinadotio, I'm definitely going to look into them.

I know the fake branch solution isn't ideal, but it's the only think I could think of to allow multiple users to do the same challenge. Do you have any other ideas?

**Pull request closed without merging**
