### PR TITLE
Ptk 39005

### PR DESCRIPTION
**Pull request by ptk-39005**
Updated files

### CODE REVIEW

**Comment by AngeloFedericoTassotti1991Prag** [comment]
> Aktualizované soubory

Zdravím

**Comment by saigha1** [comment]
Implemented DRY on codebase

**Comment by LakshmikanthanC** [comment]
hello i have update this code

**Comment by alokdubey02** [comment]
Code is updated and all test cases are passed

**Comment by Nikhil-Verma-01** [comment]
All testcase are passed and I want to contribute my contribution

**Pull request closed without merging**
